# Generated by Django 3.2.2 on 2021-06-18 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_review_ticket_userfollows'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
